version: '3.2.1'

env:
  BUCKET_NAME: aabdelre-dev
  BASE_DOMAIN: "ahmed.hypershift.devcluster.openshift.com"
  AWS_CREDS: "$HOME/.aws/credentials"
  PULL_SECRET: ~/Downloads/pull-secret.txt
  REGION: us-east-1
  NAMESPACE: clusters
  STS_CREDS: ~/.aws/sts-creds.json
  INSTANCE_TYPE: "m5.xlarge"
  REPLICAS: 3
  KUBECONFIG: "./kubeconfig"
  RELEASE_IMAGE: "quay.io/openshift-release-dev/ocp-release:4.17.3-multi"
  CLUSTER_NAME: "default-cluster"

tasks:
  default:
    cmds:
      - echo "Kubeconfig $KUBECONFIG" & sleep 1
      - echo "Cluster name $CLUSTER_NAME" & sleep 1
      - aws_install
